services:
  backend:
    build: ./backend
    container_name: infrastructure-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: infrastructure-frontend
    ports:
      - "3000:3000"
